Removed the ssd in the option menu and provided new interface for ssd
nicolasseng/teamproject-objectdetection pull request #47
Opened 2023-06-20 14:19 UTC by nicolasseng

Yolo und ssd sind nun im selben option menu wobei auch das interface für ssd geändert wurde.

2023-06-20 20:27 UTC, FredericLala reviewed
The implementation looks good, at a later point we should probably unify the looks of the UI.

But could you delete the yolov8l.pt and yolov8m.pt files, because they should already be in data/preTrainedYolo folder. Or at least they should normally be created there.
+
The yolov8_config.yaml, this file will be created individually for each user, so it should not be in the rep.

2023-06-20 22:30 UTC, ScatteredDrifter requested changes
Thanks for contributing, your works looks well mostly. 
I've added some comments regarding files that should be deleted, otherwise I'm fine with your changes.

2023-06-20 22:30 UTC, ScatteredDrifter commented on UI/uiFoundation.py
> +    appModeSelection = ["Readme File", "Run ObejctDetection", "Show the Code"];
Typo here, maybe correct before merging ^

2023-06-20 22:30 UTC, ScatteredDrifter commented on UI/uiRunningApp.py
> +    # --- /
Looks fine! Was merged from another position

2023-06-20 22:30 UTC, ScatteredDrifter commented on yolo/yolov8_config.yaml
> +train: none/images
this file should be deleted pls

2023-06-20 22:30 UTC, ScatteredDrifter commented on data/.DS_Store
delete pls, metadata not relevant for program ^

2023-06-20 22:30 UTC, ScatteredDrifter commented on yolov8l.pt
delete pls

2023-06-20 22:30 UTC, ScatteredDrifter commented on yolov8m.pt
delete pls ^

2023-06-20 22:30 UTC, ScatteredDrifter commented on UI/uiYolo.py
> +    if sourceTypeSelected == 'SSD':
not the ideal solution I think, but for now It should do the job.

2023-06-21 11:03 UTC, SimonCashew approved these changes
Alle gewünschten Änderungen vorgenommen

2023-06-24 15:28 UTC, merged